---
pool: 
  name: "Default"
trigger:
  - main
steps:
  - task: Maven@3
    inputs: 
       mavenPOMFile: 'pom.xml'
       goals: 'package'
       publishJUnitResults: true
       testResultsFiles: '**/surefire-reports/TEST-*.xml'
       javaHomeOption: '1.17'
       jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
       mavenDirectory:  /usr/share/maven 